### ISSUE TITLE
Watch should accept Path objects as well as strings

### ISSUE THREAD

**Issue by bulletmark** [rbarrois/aionotify#12]
Since Python 3.6, all the standard library accepts Path objects as well as strings as per https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep519, Ideally, aionotify should as well. I think you just call os.fspath() on the argument.

**Comment by bulletmark** [comment]
As I said in the PR I closed, os.fspath was only added in Python 3.6 but this package otherwise supports 3.4 so closing this issue.

**Comment by aharel** [comment]
Please reconsider this. I was shocked when I run into this. Now-a-days it sure feels like a bug.
And if supporting Python 3.4 is still desirable, you can always protect the code that supports pathlib.Path objects with explicit/implicit checks of the python version.
