### ISSUE TITLE
Please consider relicensing

### ISSUE THREAD

**Issue by smurfix** [rbarrois/aionotify#16]
Hi,

I'm not comfortable with signing a CLA. Also, the git log already contains a couple of people who don't appear in CREDITS (despite the *"must"* clause therein).

I thus propose to relicense to MIT or "normal" Apache.

**Comment by rbarrois** [comment]
Hi!

Are you sure you've got the right repository? I've just taken a look at the git log, and I don't see other code authors than me (although I'm quite late on pending pull requests, which might have confused your reading).

Regarding the license, what's the issue with BSD that would be solved with MIT or Apache?
