### ISSUE TITLE
Max OSX 10.13.2 cannot find libc.so.6 

### ISSUE THREAD

**Issue by riccardodivirgilio** [rbarrois/aionotify#5]
this is happening because the default location is different.
inotify module is using a different code:
https://github.com/dsoprea/PyInotify/blob/master/inotify/library.py

instead of hardcoding 'libc.so.6' is using ctypes.util.find_library, so basically to fix this issue it looks like you can just use this on line 15:

https://github.com/rbarrois/aionotify/blob/master/aionotify/base.py
_libc = ctypes.cdll.LoadLibrary(ctypes.util.find_library('c') or 'libc.so.6')

this fix seems to work.
can I create a pull request?

thanks

**Comment by ldo** [comment]
You are wasting your time. [inotify(7)](http://man7.org/linux/man-pages/man7/inotify.7.html) is a Linux-only API.

**Comment by rbarrois** [comment]
Indeed, I'm afraid this library is only useful under Linux for now.

Thanks for your interest!
